services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "42000:80"
    restart: unless-stopped
    environment:
      VITE_SUPABASE_URL: https://yoursite.supabase.co
      VITE_SUPABASE_ANON: your_secret_key
      VITE_FRONTEND_BASE_URL: https://jobtrackr.online
      VITE_SUPABASE_JOBS_TABLE: jobs_table
      VITE_SUPABASE_LINKEDIN_FUNCTION: v1/linkedin-scrape_func
