version: "3.8"

services:
  # Frontend service (React with Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build # Ensure this target is defined in your Dockerfile
    container_name: react_tracker
    restart: unless-stopped
    ports:
      - "5173:5173" # Expose port 5173 for Vite
    networks:
      - app-network

  # Backend service (Node.js with Express or similar)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build # Ensure this target is defined in your Dockerfile
    container_name: node_tracker_backend
    restart: unless-stopped
    ports:
      - "4444:4444" # Expose port 4444 for the backend API
    networks:
      - app-network

# Define a custom network for frontend and backend communication
networks:
  app-network:
    driver: bridge
