version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: react_tracker
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: node_tracker_backend
    restart: unless-stopped
    ports:
      - "4444:4444"
    environment:
      - NODE_ENV=production
