services:
  frontend:
    restart: unless-stopped
    build:
      context: . # The root of your project
      dockerfile: Dockerfile.frontend # Separate Dockerfile for frontend
    ports:
      - "5173:80" # Expose port 80 for the frontend
    environment:
      - VITE_ENV=production
      - NODE_ENV=production
      - VITE_PROXY_TARGET=backend
      - VITE_PROXY_PORT=4444
      - HOST=0.0.0.0
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4444:4444"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    command: npm run prod
