services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    container_name: node_tracker_backend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend/node_modules
    ports:
      - "4444:4444"
    command: npm run dev
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/frontend
    container_name: react_tracker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
    ports:
      - "5173:5173" # Vite default port
    command: npm run dev
    environment:
      - VITE_ENV=production
      - NODE_ENV=production
      - VITE_PROXY_TARGET=backend
      - VITE_PROXY_PORT=4444
      - HOST=0.0.0.0
    restart: unless-stopped
