export { default as Home } from "./Home";
export { default as SimpleDashboard } from "./SimpleDashboard";
export { default as Map } from "./Map";
export { default as Login } from "./Login";
export { default as Logout } from "./Logout";
export { default as AuthCallback } from "./AuthCallback";
export { default as Account } from "./Account";
export { default as PrivacyPolicy } from "./PrivacyPolicy";
export { default as Terms } from "./Terms";